name: Rerecord Issue
author: Replay.io
description: Rerecords an issue with updated sources and comments with the results
inputs:
  api-key:
    description: "Replay.io API Key"
  server-url:
    description: "Server with new sources to use while rerecording"

runs:
  using: composite
  steps:
    - name: "Rerecord Issue"
      id: "rerecord-issue"
      uses: actions/github-script@v7
      with:
        result-encoding: json
        script: |
          let apiKey = '${{ inputs.api-key }}';
          if (!apiKey) {
            apiKey = process.env.REPLAY_API_KEY || process.env.RECORD_REPLAY_API_KEY || null;
          }
          if (!apiKey) {
            throw new Error("You must provide an API key for rerecording. This can be added as an environment variable named REPLAY_API_KEY or as an `api-key` input.");
          }

          const gap = process.env.GITHUB_ACTION_PATH;

          const getIssueRecording = require(gap + '/dist/issueRecording.js');
          const { owner, repo, issueNumber, recordingId } = await getIssueRecording({
            github,
            eventPath: process.env.GITHUB_EVENT_PATH,
            repositoryName: process.env.GITHUB_REPOSITORY,
          });

          const ProtocolClient = require(gap + '/dist/protocolClient.js');
          const client = new ProtocolClient();

          const rerecordIssue = require(gap + '/dist/rerecord.js');
          const data = await rerecordIssue({
            client,
            apiKey,
            serverURL: '${{ inputs.server-url }}',
            recordingId,
          });

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: issueNumber,
            body: data,
          });
      env:
        REPLAY_API_KEY: ${{ inputs.api-key }}
